# Generated by Django 6.0.2 on 2026-02-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ParkingFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("address", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name_plural": "Parking facilities",
            },
        ),
        migrations.CreateModel(
            name="DeviceHealthScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="ParkingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=64)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="api.parkingfacility",
                    ),
                ),
            ],
            options={
                "unique_together": {("facility", "code")},
            },
        ),
        migrations.AddField(
            model_name="device",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="api.parkingzone",
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("offline", "Device offline"),
                            ("high_power", "High power usage"),
                            ("invalid_data", "Invalid data"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "alert_type"],
                        name="api_alert_device__9ac37c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParkingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_occupied", models.BooleanField()),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_logs",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="api_parking_device__4f42bf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "target_value",
                    models.FloatField(
                        help_text="Expected occupancy count or usage hours"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("zone", "Zone"), ("device", "Device")], max_length=16
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="api.device",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="api.parkingzone",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("zone__isnull", False)),
                        fields=("zone", "date"),
                        name="unique_zone_date_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("device__isnull", False)),
                        fields=("device", "date"),
                        name="unique_device_date_target",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voltage", models.FloatField()),
                ("current", models.FloatField()),
                ("power_factor", models.FloatField()),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="api_telemet_device__3625d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "timestamp"),
                        name="unique_device_timestamp_telemetry",
                    )
                ],
            },
        ),
    ]
